// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRrLueHf-I9QUvX6LzF8fU6U6xzYaQ78',
    appId: '1:934194998892:web:26738bf1605f88163b7249',
    messagingSenderId: '934194998892',
    projectId: 'photos-flutter-app',
    authDomain: 'photos-flutter-app.firebaseapp.com',
    storageBucket: 'photos-flutter-app.appspot.com',
    measurementId: 'G-0N5L3P64BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPsSi16t95jUkXdz8VTTR2huiAIjGWuDw',
    appId: '1:934194998892:android:d9e452c4eed215d83b7249',
    messagingSenderId: '934194998892',
    projectId: 'photos-flutter-app',
    storageBucket: 'photos-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAuRo7Mlho23EBa7aRN2jKe-nX3B9it0s',
    appId: '1:934194998892:ios:9b2a4b676ed274933b7249',
    messagingSenderId: '934194998892',
    projectId: 'photos-flutter-app',
    storageBucket: 'photos-flutter-app.appspot.com',
    androidClientId: '934194998892-9f19q8gdjgtdqc1tjis8arqq2v15db7o.apps.googleusercontent.com',
    iosClientId: '934194998892-be3jo0lg8v5k1i85mqd6dil2bpj1r8o1.apps.googleusercontent.com',
    iosBundleId: 'photos-flutter-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAuRo7Mlho23EBa7aRN2jKe-nX3B9it0s',
    appId: '1:934194998892:ios:8b276b640c4a4d263b7249',
    messagingSenderId: '934194998892',
    projectId: 'photos-flutter-app',
    storageBucket: 'photos-flutter-app.appspot.com',
    androidClientId: '934194998892-9f19q8gdjgtdqc1tjis8arqq2v15db7o.apps.googleusercontent.com',
    iosClientId: '934194998892-tm3fgch3sr0o79a0hk2kft9guvgtmd5r.apps.googleusercontent.com',
    iosBundleId: 'photos-flutter-app-macos',
  );
}
